name: PR Checks

on: pull_request

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run pre-commit on PR diff
        run: pre-commit run --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.sha }}

      - name: Run pytest
        run: |
          set +e
          pytest --maxfail=1 --disable-warnings -q
          code=$?
          if [ $code -eq 5 ]; then
            echo "No tests collected. Skipping."
            exit 0
          fi
          exit $code
